services:
  postgres:
    image: postgres:16-alpine
    container_name: payments-webhooks-postgres
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: payments
    ports:
      - "5433:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d:ro
      - payments-webhooks-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d payments"]
      interval: 2s
      timeout: 3s
      retries: 20

volumes:
  payments-webhooks-pgdata:
